---
##
# Deploys the ansible management user
##

# Make sure to add the password less sudo user group if configured
- block:
  - name: GROUP | Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: LINEINFILE | Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  when: ansible_ssh_user_create and ansible_ssh_user_allow_sudo

- name: USER | Create ansible management SSH user
  user:
    name: "{{ ansible_ssh_management_user }}"
    groups: "{{ ansible_ssh_user_group }}"
    append: yes
    create_home: yes
    shell: /bin/bash
  when: ansible_ssh_user_create

- name: AUTHORIZED_KEY | Deploy authorized_key for ansible management SSH user
  authorized_key:
    user: "{{ ansible_ssh_management_user }}"
    key: "{{ ansible_ssh_user_key }}"
    state: present
    validate_certs: false
  when: ansible_ssh_user_create and ansible_ssh_user_deploy_key
