---
##
# Sets up the ssh users and their authorized keys
#
# TODO - This will currently not create a new user that has no "keys"!
# TODO - The state is refering to the access keys, not the user!
##
- name: USER | Create ssh users
  user:
    name: "{{ item.0.user }}"
    create_home: yes
    shell: /bin/bash
  with_subelements:
    - "{{ ansible_ssh_users }}"
    - keys
  when: 
    - ansible_ssh_create_users
    - item.0.user != 'root' # Skip root user creation
    - item.0.user != ansible_ssh_mgm_user # Skip ansible management user creation

- name: AUTHORIZED_KEY | Deploy authorized keys for ssh users
  authorized_key:
    user: "{{ item.0.user }}" # Item index refers to the sub element
    key: "{{ item.1 }}"
    state: "{{ item.0.state | default('present') }}"
    validate_certs: false
  with_subelements:
    - "{{ ansible_ssh_users }}"
    - keys
  when:
    - ansible_ssh_create_users
    - ansible_ssh_deploy_keys
