---
##
# Secure ssh access
##
- name: LINEINFILE | Deny password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  when: ansible_ssh_secure_deny_passwd_auth
  notify: restart ssh

- name: LINEINFILE | Deny root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin without-password"
    state: present
  when: ansible_ssh_secure_deny_root_login
  notify: restart ssh

- name: LINEINFILE | Switch SSH port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port {{ ansible_ssh_secure_port }}"
    state: present
  when: ansible_ssh_secure_port
  notify: restart ssh
