---
- name: SET_FACT | Create a random new root password
  set_fact:
    new_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=12, chars=['ascii_letters', 'digits', '.!$?-+#=']) }}"
  no_log: true

- name: COPY | Write the new root password to file
  copy:
    content: "{{ new_password }}"
    dest: "{{ ansible_ssh_root_password_file }}"
    
- name: USER | Update root password
  user:
    name: root
    update_password: always
    password: "{{ new_password | password_hash('sha512') }}"
  when: ansible_ssh_create_root_password